//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.org/Alumno/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.example.org/Alumno/", IsNullable=false)]
public partial class AlumnoConsulta {
    
    private string codigo_alumnoField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigo_alumno {
        get {
            return this.codigo_alumnoField;
        }
        set {
            this.codigo_alumnoField = value;
        }
    }

    private string mensaje1 = "<?xml version='1.0' encoding='UTF-8'?><tns0:Envelope xmlns:tns0='http://schemas.xmlsoap.org/soap/envelope/' xmlns:tns1='http://www.example.org/Alumno/' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'><tns0:Header/><tns0:Body><tns1:AlumnoConsulta><codigo_alumno>";
    private string mensaje2 = "</codigo_alumno></tns1:AlumnoConsulta></tns0:Body></tns0:Envelope>";
    public string mensaje
    {
        get
        {
            return mensaje1 + codigo_alumnoField + mensaje2;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.org/Alumno/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.example.org/Alumno/", IsNullable=false)]
public partial class AlumnoConsultaRS {
    
    private string des_pagoField;
    
    private string des_estadoField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string des_pago {
        get {
            return this.des_pagoField;
        }
        set {
            this.des_pagoField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string des_estado {
        get {
            return this.des_estadoField;
        }
        set {
            this.des_estadoField = value;
        }
    }
}
